name = "falling-frost-7656"
main = "worker.js"
compatibility_date = "2024-03-20"

compatibility_flags = ["nodejs_compat"]


# Runs the scheduled() function every minute to check for gym alarms
[triggers]
crons = ["* * * * *"]

# Binds the D1 Database we created earlier
[[d1_databases]]
binding = "DB"
database_name = "abdullah-schedule-push"
database_id = "ee636566-8632-4cc7-b879-92be3bb48547"


